name: Reusable workflow user
on: 
  workflow_dispatch:
jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Runa a one-line script
        run: echo Hello, world!
    
  docker: 
    uses: ashrafalih/ResableWorkflow/blob/main/.github/workflows/buildandpublish.yml@main #<acc name/repo name/full path of the yml file>@defaltbaranch_name
    with: # to get the inputs we use with keyword
      image_name: my-test-app
      tag: $GITHUB_RUN_RUNNER
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
      
    
    
  
